application: com-159616
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: www/css

- url: /.*/img
  script: main.app

- url: /order.*
  script: main.app
  login: required

- url: /admin.*
  script: admin.admin.app
  login: admin

- url: /
  script: main.app

- url: /seeding.*
  script: admin.seeder.app
  login: admin

- url: /(\d+)/orders
  script: main.app
  login: required

- url: /test
  script: admin.test.app
  login: admin

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
